name: BuildExamplesLinux

on:
  [push, pull_request]

jobs:
  ubuntu_build_tests:
    name: Build Examples
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: '5.15.2'
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build Samples
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -GNinja -DVCG_BUILD_EXAMPLES=ON ..
        ninja
